version: '3'

services:
  server:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: 'alissonrangel/php:prod'
    container_name: server
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./php:/var/www/html    
    networks:
      - servernet
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'
    environment: 
      - MYSQL_DATABASE=meubanco
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - servernet

networks:
  servernet:
    driver: bridge

